version: "3.3"

services:
  mysql:
    image: elestio/mysql:8.0
    restart: always
    hostname: mysql
    volumes:
      - ./storage/mysql:/var/lib/mysql
    env_file:
      - ./.env
    ports:
      - "172.17.0.1:50778:3306"

  glpi:
    image: elestio/glpi:${SOFTWARE_VERSION_TAG}
    restart: always
    hostname: glpi
    ports:
      - "172.17.0.1:22571:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./storage/var/www/html/glpi/:/var/www/html/glpi
      - ./apache/php.ini:/etc/php/8.1/apache2/php.ini
    environment:
      - TIMEZONE=America/Sao_Paulo

  pma:
    image: phpmyadmin
    restart: always
    links:
      - mysql:mysql
    ports:
      - "172.17.0.1:22811:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: jr23va27
      UPLOAD_LIMIT: 500M
      MYSQL_USERNAME: glpi
      MYSQL_ROOT_PASSWORD: jr23va27
      MYSQL_DATABASE: glpi
    depends_on:
      - mysql
